@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

LibTask *-right-> "1" BookList
LibTask *-right-> "1" UniquePatronList
LibTask *-right-> "1" UniqueTagList
BookList -[hidden]down- UniqueTagList
UniqueTagList -[hidden]down- UniquePatronList

UniqueTagList *-right-> "*" Tag
UniquePatronList o-right-> Patron
BookList o-right-> Book

Patron -up-> "*" Tag
Book -down-> "*" Tag

Book *-right-> "1" BookName
Book *-down-> "1" Author
Book *-down-> "1" Isbn
Book *-down-> "1" BookStatus
BookStatus -right-> "1" "<<enum>>\nBookStatusType"

Tag -[hidden]right- Author
Author -[hidden]right- BookStatus
"<<enum>>\nBookStatusType" -[hidden]right- Isbn
BookStatus --> "0..1" Patron
Book --> "0..3" Patron

Patron *--> "1" Name
Patron *--> "1" Phone
Patron *--> "1" Email
Patron *--> "1" Address
Patron *--> "1" Id
@enduml
