@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":LibTaskParser" as LibTaskParser LOGIC_COLOR
participant ":PatronCommandParser" as PatronCommandParser LOGIC_COLOR
participant ":DeletePatronCommandParser" as DeletePatronCommandParser LOGIC_COLOR
participant "d:DeletePatronCommand" as DeletePatronCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("patron delete 1")
activate LogicManager

LogicManager -> LibTaskParser : parseCommand("patron delete 1")
activate LibTaskParser

create PatronCommandParser
LibTaskParser -> PatronCommandParser
activate PatronCommandParser

PatronCommandParser --> LibTaskParser
deactivate PatronCommandParser

LibTaskParser -> PatronCommandParser : parse("delete 1")
activate PatronCommandParser

create DeletePatronCommandParser
PatronCommandParser -> DeletePatronCommandParser
activate DeletePatronCommandParser

DeletePatronCommandParser --> PatronCommandParser
deactivate DeletePatronCommandParser

PatronCommandParser -> DeletePatronCommandParser : parse("1")
activate DeletePatronCommandParser

create DeletePatronCommand
DeletePatronCommandParser -> DeletePatronCommand
activate DeletePatronCommand

DeletePatronCommand --> DeletePatronCommandParser : d
deactivate DeletePatronCommand

DeletePatronCommandParser --> PatronCommandParser : d
deactivate DeletePatronCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeletePatronCommandParser -[hidden]-> LibTaskParser
destroy DeletePatronCommandParser

PatronCommandParser --> LibTaskParser : d
deactivate PatronCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
PatronCommandParser -[hidden]-> LibTaskParser
destroy PatronCommandParser

LibTaskParser --> LogicManager : d
deactivate LibTaskParser

LogicManager -> DeletePatronCommand : execute()
activate DeletePatronCommand

DeletePatronCommand -> Model : deletePatron(1)
activate Model

Model --> DeletePatronCommand
deactivate Model

create CommandResult
DeletePatronCommand -> CommandResult
activate CommandResult

CommandResult --> DeletePatronCommand
deactivate CommandResult

DeletePatronCommand --> LogicManager : result
deactivate DeletePatronCommand

[<--LogicManager
deactivate LogicManager
@enduml
