@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "LibTask Storage" #F4F6F6{
Class "<<interface>>\nLibTaskStorage" as LibTaskStorage
Class JsonLibTaskStorage
Class JsonSerializableLibTask
Class JsonAdaptedPerson
Class JsonAdaptedTag
Class JsonAdaptedBook
Class JsonAdaptedBookStatus
Class JsonAdaptedAuthor
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" LibTaskStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> LibTaskStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonLibTaskStorage .up.|> LibTaskStorage
JsonLibTaskStorage ..> JsonSerializableLibTask
JsonSerializableLibTask ---> "*" JsonAdaptedPerson
JsonSerializableLibTask --> "*" JsonAdaptedBook
JsonAdaptedPerson --> "*" JsonAdaptedTag
JsonAdaptedBook --> "*" JsonAdaptedAuthor
JsonAdaptedBook --> "1" JsonAdaptedBookStatus
JsonAdaptedBook --> "0..3" JsonAdaptedPerson : requested by >
JsonAdaptedBookStatus -> "0..1" JsonAdaptedPerson : borrowed by >

JsonAdaptedBookStatus -[hidden]left-JsonAdaptedAuthor
@enduml
