title: "LibTask"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: Kramdown

repository: "se-edu/addressbook-level3"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
